### PR TITLE
Make permissions usable by the world

### PR DESCRIPTION
**Pull request by baltzell**
This could go in the build system for clas12-mcgen if you don't want it here.

### CODE REVIEW

**Comment by tylern4** [comment]
LGTM!

**Comment by baltzell** [comment]
Unless there's other foreseen changes coming soon, can you make a new git tag?

**Comment by tylern4** [comment]
I think Caleb found one more bug I'm going to fix this week and then get a new release out.

**Comment by tylern4** [comment]
@baltzell tag v1.3 includes these changes.

**Pull request merged**
